### ISSUE TITLE
Email should be hidden in config.ini

### ISSUE THREAD

**Issue by YahyaOukharta** [moerradi/ethmine#1]
In nanopool, the email is used as a **password** to change the minimum balance for withdrawal.
Maybe use [Github Encrypted Secrets](https://docs.github.com/en/actions/reference/encrypted-secrets)

**Comment by moerradi** [comment]
I'm just too lazy to implement it lol

**Comment by YahyaOukharta** [comment]
Makes sense ! I'll make a bot to change your withdrawal limit whenever you reach the one you set, so you can withdraw in a 3 years or something !
